# -*- coding: utf-8 -*-
"""Actividad Bloomberg ARMA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T00gx_wOYPVpGgd2nxUzMCKRpuPsXhqk
"""

# Import required libraries
import pandas as pd
import numpy as np
from google.colab import files
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import matplotlib.pyplot as plt

# Upload Excel files for META, AMZN, GOOGL (1-min and 3-min)
print("Please upload META 1-min Excel file")
meta_1m_upload = files.upload()
meta_1m_filename = list(meta_1m_upload.keys())[0]
meta_1m_df = pd.read_excel(meta_1m_filename)

print("Please upload META 3-min Excel file")
meta_3m_upload = files.upload()
meta_3m_filename = list(meta_3m_upload.keys())[0]
meta_3m_df = pd.read_excel(meta_3m_filename)

print("Please upload AMZN 1-min Excel file")
amzn_1m_upload = files.upload()
amzn_1m_filename = list(amzn_1m_upload.keys())[0]
amzn_1m_df = pd.read_excel(amzn_1m_filename)

print("Please upload AMZN 3-min Excel file")
amzn_3m_upload = files.upload()
amzn_3m_filename = list(amzn_3m_upload.keys())[0]
amzn_3m_df = pd.read_excel(amzn_3m_filename)

print("Please upload GOOGL 1-min Excel file")
googl_1m_upload = files.upload()
googl_1m_filename = list(googl_1m_upload.keys())[0]
googl_1m_df = pd.read_excel(googl_1m_filename)

print("Please upload GOOGL 3-min Excel file")
googl_3m_upload = files.upload()
googl_3m_filename = list(googl_3m_upload.keys())[0]
googl_3m_df = pd.read_excel(googl_3m_filename)

# Print available columns for verification
print("\nMETA 1-min columns:", list(meta_1m_df.columns))
print("META 3-min columns:", list(meta_3m_df.columns))
print("AMZN 1-min columns:", list(amzn_1m_df.columns))
print("AMZN 3-min columns:", list(amzn_3m_df.columns))
print("GOOGL 1-min columns:", list(googl_1m_df.columns))
print("GOOGL 3-min columns:", list(googl_3m_df.columns))

# Ask user for the correct column name for closing prices
close_column = input("Please enter the column name containing closing prices: ")

# Extract closing prices using user-specified column name
try:
    meta_1m_close = meta_1m_df[close_column]
    meta_3m_close = meta_3m_df[close_column]
    amzn_1m_close = amzn_1m_df[close_column]
    amzn_3m_close = amzn_3m_df[close_column]
    googl_1m_close = googl_1m_df[close_column]
    googl_3m_close = googl_3m_df[close_column]
except KeyError:
    print(f"Error: Column '{close_column}' not found in one or more DataFrames")
    print("Please check the column names and try again")
    raise

# Ensure all series have the same length
min_length = min(len(meta_1m_close), len(meta_3m_close), len(amzn_1m_close),
                 len(amzn_3m_close), len(googl_1m_close), len(googl_3m_close))
meta_1m_close = meta_1m_close[:min_length]
meta_3m_close = meta_3m_close[:min_length]
amzn_1m_close = amzn_1m_close[:min_length]
amzn_3m_close = amzn_3m_close[:min_length]
googl_1m_close = googl_1m_close[:min_length]
googl_3m_close = googl_3m_close[:min_length]

# Dictionary to store series for easier iteration
series_dict = {
    "META_1m": meta_1m_close,
    "META_3m": meta_3m_close,
    "AMZN_1m": amzn_1m_close,
    "AMZN_3m": amzn_3m_close,
    "GOOGL_1m": googl_1m_close,
    "GOOGL_3m": googl_3m_close
}

# Data validation
print("\nData Validation:")
for name, series in series_dict.items():
    print(f"{name}:")
    print(f"  Length: {len(series)}")
    print(f"  NaN count: {series.isna().sum()}")
    print(f"  Infinite values: {np.isinf(series).sum()}")
    print(f"  Variance: {series.var():.4f}")

# Check if min_length is sufficient
if min_length < 50:
    print("Warning: Data length is very short (%d). Cointegration tests may fail." % min_length)

# Function for unit root tests with interpretation
def unit_root_tests(series, name):
    print(f"\nUnit Root Tests for {name}:")

    # ADF Test
    adf_result = adfuller(series)
    print("ADF Test:")
    print(f'ADF Statistic: {adf_result[0]:.4f}')
    print(f'p-value: {adf_result[1]:.4f}')
    print(f'Critical Values: {adf_result[4]}')
    print("Interpretation:")
    if adf_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")

    # KPSS Test
    kpss_result = kpss(series)
    print("\nKPSS Test:")
    print(f'KPSS Statistic: {kpss_result[0]:.4f}')
    print(f'p-value: {kpss_result[1]:.4f}')
    print(f'Critical Values: {kpss_result[3]}')
    print("Interpretation:")
    if kpss_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is non-stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be stationary")

# Perform unit root tests for all series
for name, series in series_dict.items():
    unit_root_tests(series, name)

# Cointegration test with interpretation and error handling
def cointegration_test(df, name1, name2):
    # Check correlation to detect collinearity
    corr = df[name1].corr(df[name2])
    print(f"Correlation between {name1} and {name2}: {corr:.4f}")
    if abs(corr) > 0.99:
        print(f"Warning: High collinearity (|corr| > 0.99). Cointegration test may fail.")

    # Try with k_ar_diff=1, fallback to 0 if it fails
    for k_ar_diff in [1, 0]:
        try:
            result = coint_johansen(df, det_order=0, k_ar_diff=k_ar_diff)
            print(f"\nJohansen Cointegration Test between {name1} and {name2} (k_ar_diff={k_ar_diff}):")
            print(f"Trace statistic: {result.lr1}")
            print(f"Critical values (90%, 95%, 99%): {result.cvt}")
            print("Interpretation:")
            for i in range(len(result.lr1)):
                if result.lr1[i] > result.cvt[i, 1]:
                    print(f"  - r = {i}: Cointegration exists at 95% confidence level")
                    print(f"    Trace statistic ({result.lr1[i]:.2f}) > 95% critical value ({result.cvt[i, 1]:.2f})")
                else:
                    print(f"  - r = {i}: No cointegration at 95% confidence level")
                    print(f"    Trace statistic ({result.lr1[i]:.2f}) <= 95% critical value ({result.cvt[i, 1]:.2f})")
            if result.lr1[0] > result.cvt[0, 1]:
                print(f"Conclusion: {name1} and {name2} are cointegrated")
            else:
                print(f"Conclusion: No evidence of cointegration between {name1} and {name2}")
            return
        except np.linalg.LinAlgError as e:
            print(f"LinAlgError with k_ar_diff={k_ar_diff}: {e}")
            if k_ar_diff == 0:
                print(f"Skipping cointegration test for {name1} vs {name2} due to persistent error.")
            continue
    print(f"Failed to perform cointegration test for {name1} vs {name2}.")

# Perform pairwise cointegration tests for 1-min and 3-min separately
pairs_1m = [
    ("META_1m", "AMZN_1m", meta_1m_close, amzn_1m_close),
    ("META_1m", "GOOGL_1m", meta_1m_close, googl_1m_close),
    ("AMZN_1m", "GOOGL_1m", amzn_1m_close, googl_1m_close)
]
pairs_3m = [
    ("META_3m", "AMZN_3m", meta_3m_close, amzn_3m_close),
    ("META_3m", "GOOGL_3m", meta_3m_close, googl_3m_close),
    ("AMZN_3m", "GOOGL_3m", amzn_3m_close, googl_3m_close)
]

print("\nCointegration Tests for 1-min Data:")
for name1, name2, series1, series2 in pairs_1m:
    coint_df = pd.DataFrame({name1: series1, name2: series2}).dropna()
    cointegration_test(coint_df, name1, name2)

print("\nCointegration Tests for 3-min Data:")
for name1, name2, series1, series2 in pairs_3m:
    coint_df = pd.DataFrame({name1: series1, name2: series2}).dropna()
    cointegration_test(coint_df, name1, name2)

# Function to find best ARIMA model with interpretation
def find_best_arima(series, name, max_p=3, max_d=2, max_q=3):
    best_aic = float('inf')
    best_order = None

    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except:
                    continue

    print(f"\nBest ARIMA model for {name}:")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    print(f"  - p={best_order[0]}: {best_order[0]} autoregressive term(s)")
    print(f"  - d={best_order[1]}: {best_order[1]} difference(s) needed for stationarity")
    print(f"  - q={best_order[2]}: {best_order[2]} moving average term(s)")
    return best_order

# Find and fit best ARIMA models for all series
arima_orders = {}
arima_models = {}
for name, series in series_dict.items():
    order = find_best_arima(series, name)
    arima_orders[name] = order
    arima_models[name] = ARIMA(series, order=order).fit()

# Forecast next 30 periods
forecast_steps = 30
forecasts = {}
for name, model in arima_models.items():
    forecasts[name] = model.forecast(steps=forecast_steps)

# Create forecast index
last_index = min_length - 1
forecast_index = range(last_index + 1, last_index + 1 + forecast_steps)

# Plot all series with forecasts
plt.figure(figsize=(14, 8))
colors = ['blue', 'cyan', 'green', 'lime', 'purple', 'magenta']
i = 0
for name, series in series_dict.items():
    plt.plot(series, label=f'{name} Historical', color=colors[i], alpha=0.5)
    plt.plot(forecast_index, forecasts[name], label=f'{name} Forecast', color=colors[i], linestyle='--')
    i += 1
plt.title('META, AMZN, GOOGL 1-min and 3-min Closing Prices with Forecasts')
plt.legend()
plt.show()

# Detailed forecast plot with confidence intervals and interpretation
def plot_forecast(model, series, name, steps=30):
    forecast_obj = model.get_forecast(steps=steps)
    forecast = forecast_obj.predicted_mean
    conf_int = forecast_obj.conf_int()

    forecast_index = range(len(series), len(series) + steps)

    plt.figure(figsize=(12, 6))
    plt.plot(series, label=f'{name} Historical')
    plt.plot(forecast_index, forecast, label='Forecast', color='red')
    plt.fill_between(forecast_index,
                     conf_int.iloc[:, 0],
                     conf_int.iloc[:, 1],
                     color='pink',
                     alpha=0.3,
                     label='95% Confidence Interval')
    plt.title(f'{name} Price Forecast')
    plt.legend()
    plt.show()

    # Forecast interpretation
    last_value = series.iloc[-1]
    mean_forecast = forecast.mean()
    print(f"\nForecast Interpretation for {name}:")
    print(f"Last observed value: {last_value:.2f}")
    print(f"Average forecast value: {mean_forecast:.2f}")
    print(f"Forecast change: {mean_forecast - last_value:.2f}")
    if mean_forecast > last_value:
        print("Trend: Upward forecast trend")
    elif mean_forecast < last_value:
        print("Trend: Downward forecast trend")
    else:
        print("Trend: Flat forecast trend")
    print(f"95% CI range at period {steps}: [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")

# Generate detailed forecast plots and interpretations
for name, model in arima_models.items():
    plot_forecast(model, series_dict[name], name)

# Print forecast values for next 5 periods
for name, forecast in forecasts.items():
    print(f"\n{name} Forecast Values (next 5 periods):")
    print(forecast[:5])