# -*- coding: utf-8 -*-
"""ARIMA Mayo 1 Series de Tiempo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d5L-in56AUDUwTkP1_Ijup0OTtDSiOps
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np
from google.colab import files
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller, coint
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# Upload Excel files for Intel, Chevron, Boeing (5-min and 30-min)
print("Please upload Intel 5-min Excel file (e.g., PY - Intel - 5min.xlsx)")
intel_5m_upload = files.upload()
intel_5m_filename = list(intel_5m_upload.keys())[0]
intel_5m_df = pd.read_excel(intel_5m_filename)

print("Please upload Intel 30-min Excel file (e.g., PY - Intel - 30 min.xlsx)")
intel_30m_upload = files.upload()
intel_30m_filename = list(intel_30m_upload.keys())[0]
intel_30m_df = pd.read_excel(intel_30m_filename)

print("Please upload Chevron 5-min Excel file (e.g., PY - Chevron - 5 min.xlsx)")
chevron_5m_upload = files.upload()
chevron_5m_filename = list(chevron_5m_upload.keys())[0]
chevron_5m_df = pd.read_excel(chevron_5m_filename)

print("Please upload Chevron 30-min Excel file (e.g., PY - Chevron - 30min.xlsx)")
chevron_30m_upload = files.upload()
chevron_30m_filename = list(chevron_30m_upload.keys())[0]
chevron_30m_df = pd.read_excel(chevron_30m_filename)

print("Please upload Boeing 5-min Excel file (e.g., PY - Boeing - 5min.xlsx)")
boeing_5m_upload = files.upload()
boeing_5m_filename = list(boeing_5m_upload.keys())[0]
boeing_5m_df = pd.read_excel(boeing_5m_filename)

print("Please upload Boeing 30-min Excel file (e.g., PY - Boeing - 30 min.xlsx)")
boeing_30m_upload = files.upload()
boeing_30m_filename = list(boeing_30m_upload.keys())[0]
boeing_30m_df = pd.read_excel(boeing_30m_filename)

# Print available columns for verification
print("\nIntel 5-min columns:", list(intel_5m_df.columns))
print("Intel 30-min columns:", list(intel_30m_df.columns))
print("Chevron 5-min columns:", list(chevron_5m_df.columns))
print("Chevron 30-min columns:", list(chevron_30m_df.columns))
print("Boeing 5-min columns:", list(boeing_5m_df.columns))
print("Boeing 30-min columns:", list(boeing_30m_df.columns))

# Ask user for the correct column name for closing prices
close_column = input("Please enter the column name containing closing prices (press Enter for 'Close'): ") or 'Close'

# Extract closing prices using user-specified column name
try:
    intel_5m_close = intel_5m_df[close_column]
    intel_30m_close = intel_30m_df[close_column]
    chevron_5m_close = chevron_5m_df[close_column]
    chevron_30m_close = chevron_30m_df[close_column]
    boeing_5m_close = boeing_5m_df[close_column]
    boeing_30m_close = boeing_30m_df[close_column]
except KeyError:
    print(f"Error: Column '{close_column}' not found in one or more DataFrames")
    print("Please check the column names and try again")
    raise

# Ensure all series have the same length
min_length = min(len(intel_5m_close), len(intel_30m_close), len(chevron_5m_close),
                 len(chevron_30m_close), len(boeing_5m_close), len(boeing_30m_close))
intel_5m_close = intel_5m_close[:min_length]
intel_30m_close = intel_30m_close[:min_length]
chevron_5m_close = chevron_5m_close[:min_length]
chevron_30m_close = chevron_30m_close[:min_length]
boeing_5m_close = boeing_5m_close[:min_length]
boeing_30m_close = boeing_30m_close[:min_length]

# Dictionary to store series for easier iteration
series_dict = {
    "Intel_5min": intel_5m_close,
    "Intel_30min": intel_30m_close,
    "Chevron_5min": chevron_5m_close,
    "Chevron_30min": chevron_30m_close,
    "Boeing_5min": boeing_5m_close,
    "Boeing_30min": boeing_30m_close
}

# Data validation
print("\nData Validation:")
for name, series in series_dict.items():
    print(f"{name}:")
    print(f"  Length: {len(series)}")
    print(f"  NaN count: {series.isna().sum()}")
    print(f"  Infinite values: {np.isinf(series).sum()}")
    print(f"  Variance: {series.var():.4f}")

# Check if min_length is sufficient
if min_length < 50:
    print("Warning: Data length is very short (%d). Cointegration tests may be unreliable." % min_length)

# Random Walk Test
def random_walk_test(series, name):
    print(f"\nRandom Walk Test for {name}:")
    diff = series.diff().dropna()
    if np.var(diff) < 1e-5:
        print(f"{name} resembles a random walk (low variance in differences).")
    else:
        print(f"{name} does not clearly exhibit random walk behavior.")

# Unit Root Test (ADF only)
def unit_root_test(series, name):
    print(f"\nUnit Root Test (ADF) for {name}:")
    adf_result = adfuller(series)
    print(f'ADF Statistic: {adf_result[0]:.4f}')
    print(f'p-value: {adf_result[1]:.4f}')
    print(f'Critical Values: {adf_result[4]}')
    print("Interpretation:")
    if adf_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")

# Cointegration Test (Engle-Granger)
def cointegration_test(series1, series2, name1, name2):
    print(f"\nCointegration Test (Engle-Granger) between {name1} and {name2}:")
    try:
        score, p_value, _ = coint(series1, series2)
        print(f'Cointegration test statistic: {score:.4f}')
        print(f'p-value: {p_value:.4f}')
        if p_value < 0.05:
            print(f"Interpretation: {name1} and {name2} are cointegrated.")
        else:
            print(f"Interpretation: {name1} and {name2} are not cointegrated.")
    except Exception as e:
        print(f"Error in cointegration test: {e}")

# Function to find best ARIMA model and plot fit
def find_best_arima(series, name, max_p=2, max_d=1, max_q=2):
    print(f"Fitting ARIMA for {name}...")
    best_aic = float('inf')
    best_order = None
    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except Exception as e:
                    print(f"  Failed ARIMA({p},{d},{q}) for {name}: {e}")
                    continue
    if best_order is None:
        print(f"Error: No valid ARIMA model found for {name}. Skipping.")
        return None
    print(f"\nBest ARIMA model for {name}:")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    print(f"  - p={best_order[0]}: {best_order[0]} autoregressive term(s)")
    print(f"  - d={best_order[1]}: {best_order[1]} difference(s) needed for stationarity")
    print(f"  - q={best_order[2]}: {best_order[2]} moving average term(s)")
    # Plot ARIMA fit and residuals
    try:
        model = ARIMA(series, order=best_order).fit()
        fitted_values = model.fittedvalues
        residuals = model.resid
        plt.figure(figsize=(12, 8))
        # Subplot 1: Historical vs Fitted
        plt.subplot(2, 1, 1)
        plt.plot(series, label='Historical', color='blue')
        plt.plot(fitted_values, label='ARIMA Fitted', color='red', linestyle='--')
        plt.title(f'ARIMA Fit for {name} (Order {best_order})')
        plt.legend()
        # Subplot 2: Residuals
        plt.subplot(2, 1, 2)
        plt.plot(residuals, label='Residuals', color='green')
        plt.axhline(0, color='black', linestyle='--', alpha=0.5)
        plt.title('Residuals of ARIMA Model')
        plt.legend()
        plt.tight_layout()
        plt.savefig(f'{name}_arima_fit.png')
        plt.show()
        plt.close()
    except Exception as e:
        print(f"Error plotting ARIMA fit for {name}: {e}")
    return best_order

# Perform tests and ARIMA modeling for all series
arima_orders = {}
arima_models = {}
print("\nStarting ARIMA modeling...")
for name, series in series_dict.items():
    random_walk_test(series, name)
    unit_root_test(series, name)
    order = find_best_arima(series, name)
    if order is None:
        arima_orders[name] = None
        arima_models[name] = None
        continue
    try:
        model = ARIMA(series, order=order).fit()
        arima_orders[name] = order
        arima_models[name] = model
        print(f"ARIMA model fitted for {name}.")
    except Exception as e:
        print(f"Error fitting final ARIMA model for {name}: {e}")
        arima_orders[name] = order
        arima_models[name] = None

# Forecast next 30 periods
forecast_steps = 30
forecasts = {}
print("\nGenerating forecasts...")
for name, model in arima_models.items():
    if model is None:
        print(f"Skipping forecast for {name} due to model fitting error.")
        forecasts[name] = pd.Series([np.nan] * forecast_steps)
        continue
    try:
        forecasts[name] = model.forecast(steps=forecast_steps)
        print(f"Forecast generated for {name}.")
    except Exception as e:
        print(f"Error generating forecast for {name}: {e}")
        forecasts[name] = pd.Series([np.nan] * forecast_steps)

# Create forecast index
last_index = min_length - 1
forecast_index = range(last_index + 1, last_index + 1 + forecast_steps)

# Plot all series with forecasts
print("\nPlotting combined series with forecasts...")
plt.figure(figsize=(14, 8))
colors = ['blue', 'cyan', 'green', 'lime', 'purple', 'magenta']
i = 0
for name, series in series_dict.items():
    plt.plot(series, label=f'{name} Historical', color=colors[i], alpha=0.5)
    plt.plot(forecast_index, forecasts[name], label=f'{name} Forecast', color=colors[i], linestyle='--')
    i += 1
plt.title('Intel, Chevron, Boeing 5-min and 30-min Closing Prices with Forecasts')
plt.legend()
plt.savefig('combined_forecast.png')
plt.show()
plt.close()

# Detailed forecast plot with confidence intervals and interpretation
def plot_forecast(model, series, name, steps=30):
    print(f"\nPlotting forecast for {name}...")
    if model is None:
        print(f"Skipping plot for {name} due to model fitting error.")
        return
    try:
        forecast_obj = model.get_forecast(steps=steps)
        forecast = forecast_obj.predicted_mean
        conf_int = forecast_obj.conf_int()
        forecast_index = range(len(series), len(series) + steps)
        plt.figure(figsize=(12, 6))
        plt.plot(series, label=f'{name} Historical')
        plt.plot(forecast_index, forecast, label='Forecast', color='red')
        plt.fill_between(forecast_index,
                         conf_int.iloc[:, 0],
                         conf_int.iloc[:, 1],
                         color='pink',
                         alpha=0.3,
                         label='95% Confidence Interval')
        plt.title(f'{name} Price Forecast')
        plt.legend()
        plt.savefig(f'{name}_forecast.png')
        plt.show()
        plt.close()
        # Forecast interpretation
        last_value = series.iloc[-1]
        mean_forecast = forecast.mean()
        print(f"\nForecast Interpretation for {name}:")
        print(f"Last observed value: {last_value:.2f}")
        print(f"Average forecast value: {mean_forecast:.2f}")
        print(f"Forecast change: {mean_forecast - last_value:.2f}")
        if mean_forecast > last_value:
            print("Trend: Upward forecast trend")
        elif mean_forecast < last_value:
            print("Trend: Downward forecast trend")
        else:
            print("Trend: Flat forecast trend")
        print(f"95% CI range at period {steps}: [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")
    except Exception as e:
        print(f"Error plotting forecast for {name}: {e}")

# Generate detailed forecast plots and interpretations
for name, model in arima_models.items():
    plot_forecast(model, series_dict[name], name)

# Perform pairwise cointegration tests for 5-min and 30-min separately
pairs_5m = [
    ("Intel_5min", "Chevron_5min", intel_5m_close, chevron_5m_close),
    ("Intel_5min", "Boeing_5min", intel_5m_close, boeing_5m_close),
    ("Chevron_5min", "Boeing_5min", chevron_5m_close, boeing_5m_close)
]
pairs_30m = [
    ("Intel_30min", "Chevron_30min", intel_30m_close, chevron_30m_close),
    ("Intel_30min", "Boeing_30min", intel_30m_close, boeing_30m_close),
    ("Chevron_30min", "Boeing_30min", chevron_30m_close, boeing_30m_close)
]

print("\nCointegration Tests for 5-min Data:")
for name1, name2, series1, series2 in pairs_5m:
    cointegration_test(series1, series2, name1, name2)

print("\nCointegration Tests for 30-min Data:")
for name1, name2, series1, series2 in pairs_30m:
    cointegration_test(series1, series2, name1, name2)

# Print forecast values for next 5 periods
print("\nForecast Values for Next 5 Periods:")
for name, forecast in forecasts.items():
    print(f"\n{name} Forecast Values (next 5 periods):")
    print(forecast[:5])