# -*- coding: utf-8 -*-
"""GM vs. NU vs. Microsoft vs. Robinhood (30 min)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E_8YIvSFq9-eb_DqNWtxsAhOxEWhRkLS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller, coint
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.arima.model import ARIMA
from datetime import datetime, timedelta
from google.colab import files
import itertools
import warnings
warnings.filterwarnings("ignore")

# Función para convertir fechas de Excel a datetime (si es numérico)
def excel_date_to_datetime(excel_date):
    if pd.api.types.is_numeric_dtype(excel_date):
        return pd.to_datetime('1899-12-30') + pd.to_timedelta(excel_date, unit='D')
    return excel_date  # Retorna tal cual si ya es datetime

# Solicitar la carga de archivos
print("Por favor, sube los archivos Excel de Robinhood, Microsoft, NU y General Motors.")
uploaded = files.upload()

# Cargar datos desde los archivos subidos
try:
    # Buscar archivos, considerando posibles renombramientos por Colab
    robinhood_file = next((f for f in uploaded.keys() if 'ROBINHOOD' in f.upper()), None)
    microsoft_file = next((f for f in uploaded.keys() if 'MICROSOFT' in f.upper()), None)
    nu_file = next((f for f in uploaded.keys() if 'NU' in f.upper()), None)
    gm_file = next((f for f in uploaded.keys() if 'GENERAL MOTOR' in f.upper() or 'GM' in f.upper()), None)
    if not all([robinhood_file, microsoft_file, nu_file, gm_file]):
        raise ValueError("No se encontraron todos los archivos Excel esperados (Robinhood, Microsoft, NU, General Motors).")
    robinhood_df = pd.read_excel(robinhood_file)
    microsoft_df = pd.read_excel(microsoft_file)
    nu_df = pd.read_excel(nu_file)
    gm_df = pd.read_excel(gm_file)
except Exception as e:
    print(f"Error al cargar los archivos Excel: {e}")
    raise

# Crear un diccionario de DataFrames
stocks = {
    'Robinhood': robinhood_df,
    'Microsoft': microsoft_df,
    'NU': nu_df,
    'General Motors': gm_df
}

# Imprimir nombres de columnas para depuración
for name, df in stocks.items():
    print(f"Columnas del DataFrame de {name}:", df.columns.tolist())

# Verificar columnas requeridas
required_columns = ['Date', 'Close']
for name, df in stocks.items():
    if not all(col in df.columns for col in required_columns):
        raise KeyError(f"Faltan columnas requeridas en el DataFrame de {name}. Esperado: {required_columns}")

# Convertir fechas de Excel a datetime si es necesario y establecer Date como índice
for name, df in stocks.items():
    if not pd.api.types.is_datetime64_any_dtype(df['Date']):
        df['Date'] = excel_date_to_datetime(df['Date'])
    df['Date'] = pd.to_datetime(df['Date'])
    df.set_index('Date', inplace=True)
    # Manejar valores faltantes con forward fill
    df['Close'].fillna(method='ffill', inplace=True)
    # Resample para asegurar frecuencia consistente de 30 minutos
    stocks[name] = df.resample('30T').ffill()

# Alinear los DataFrames a su índice temporal común
common_index = stocks['Robinhood'].index
for name in stocks:
    common_index = common_index.intersection(stocks[name].index)
for name in stocks:
    stocks[name] = stocks[name].loc[common_index]

# Verificar longitudes después de la alineación
for name, df in stocks.items():
    print(f"Longitud del DataFrame de {name}: {len(df)}")
if len(set(len(df) for df in stocks.values())) > 1:
    raise ValueError("Los DataFrames tienen diferentes longitudes después de la alineación.")

# Graficar la serie temporal original
plt.figure(figsize=(12, 6))
for name, df in stocks.items():
    plt.plot(df['Close'], label=name)
plt.title('Precios de Acciones de Robinhood, Microsoft, NU y General Motors (30-Minutos)')
plt.xlabel('Tiempo')
plt.ylabel('Precio de Cierre (USD)')
plt.legend()
plt.grid(True)
plt.show()

# Prueba de Estacionariedad (Prueba ADF)
def adf_test(series, name):
    result = adfuller(series.dropna())
    print(f'Prueba ADF para {name}:')
    print(f'Estadístico ADF: {result[0]}')
    print(f'valor-p: {result[1]}')
    print('Estacionario' if result[1] < 0.05 else 'No Estacionario')
    return result[1] < 0.05

# Realizar la prueba ADF en las series originales y diferenciar si es necesario
stationarity_results = {}
diff_series = {}
for name, df in stocks.items():
    is_stationary = adf_test(df['Close'], name)
    stationarity_results[name] = is_stationary
    diff_series[name] = df['Close'].diff().dropna() if not is_stationary else df['Close']
    if not is_stationary:
        adf_test(diff_series[name], f"{name} Diferenciada")

# Graficar las series diferenciadas si alguna no es estacionaria
if any(not is_stationary for is_stationary in stationarity_results.values()):
    plt.figure(figsize=(12, 6))
    for name in stocks:
        plt.plot(diff_series[name], label=f"{name} Diferenciada")
    plt.title('Precios de Acciones Diferenciados (30-Minutos)')
    plt.xlabel('Tiempo')
    plt.ylabel('Diferencia de Precio')
    plt.legend()
    plt.grid(True)
    plt.show()

# Prueba de Cointegración para cada par de acciones
stock_names = list(stocks.keys())
for stock1, stock2 in itertools.combinations(stock_names, 2):
    score, p_value, _ = coint(stocks[stock1]['Close'], stocks[stock2]['Close'])
    print(f'Prueba de Cointegración entre {stock1} y {stock2}:')
    print(f'valor-p: {p_value}')
    print('Cointegradas' if p_value < 0.05 else 'No Cointegradas')

# Modelo AR
def fit_ar_model(series, name, lags=5):
    model = AutoReg(series, lags=lags).fit()
    print(f'Modelo AR({lags}) para {name}:')
    print(model.summary())

    # Pronóstico: 30 minutos es 1 paso a 30-min de frecuencia
    forecast = model.predict(start=len(series), end=len(series))  # 1 paso a 30-min de frecuencia

    # Gráfico
    plt.figure(figsize=(12, 6))
    plt.plot(series[-50:], label='Actual')
    forecast_index = pd.date_range(start=series.index[-1] + timedelta(minutes=30), periods=1, freq='30T')
    plt.plot(forecast_index, forecast, label='Pronóstico', linestyle='--')
    plt.title(f'Pronóstico AR({lags}) para {name} (Próximo Intervalo de 30 Minutos)')
    plt.xlabel('Tiempo')
    plt.ylabel('Precio de Cierre')
    plt.legend()
    plt.grid(True)
    plt.show()

    return model

# Ajustar modelos AR para cada acción
ar_models = {}
for name in stocks:
    ar_models[name] = fit_ar_model(diff_series[name], name)

# Modelo ARMA (asumiendo ARMA(2,2))
def fit_arma_model(series, name, order=(2,2)):
    model = ARIMA(series, order=(order[0], 0, order[1])).fit()
    print(f'Modelo ARMA({order[0]},{order[1]}) para {name}:')
    print(model.summary())

    # Pronóstico: 1 paso a 30-min de frecuencia
    forecast = model.forecast(steps=1)

    # Gráfico
    plt.figure(figsize=(12, 6))
    plt.plot(series[-50:], label='Actual')
    forecast_index = pd.date_range(start=series.index[-1] + timedelta(minutes=30), periods=1, freq='30T')
    plt.plot(forecast_index, forecast, label='Pronóstico', linestyle='--')
    plt.title(f'Pronóstico ARMA({order[0]},{order[1]}) para {name} (Próximo Intervalo de 30 Minutos)')
    plt.xlabel('Tiempo')
    plt.ylabel('Precio de Cierre')
    plt.legend()
    plt.grid(True)
    plt.show()

    return model

# Ajustar modelos ARMA para cada acción
arma_models = {}
for name in stocks:
    arma_models[name] = fit_arma_model(diff_series[name], name)

# Modelo ARIMA (asumiendo ARIMA(2,1,2) si no es estacionario, sino ARIMA(2,0,2))
def fit_arima_model(series, name, order=(2,1,2)):
    model = ARIMA(series, order=order).fit()
    print(f'Modelo ARIMA({order[0]},{order[1]},{order[2]}) para {name}:')
    print(model.summary())

    # Pronóstico: 1 paso a 30-min de frecuencia
    forecast = model.forecast(steps=1)

    # Gráfico
    plt.figure(figsize=(12, 6))
    plt.plot(series[-50:], label='Actual')
    forecast_index = pd.date_range(start=series.index[-1] + timedelta(minutes=30), periods=1, freq='30T')
    plt.plot(forecast_index, forecast, label='Pronóstico', linestyle='--')
    plt.title(f'Pronóstico ARIMA({order[0]},{order[1]},{order[2]}) para {name} (Próximo Intervalo de 30 Minutos)')
    plt.xlabel('Tiempo')
    plt.ylabel('Precio de Cierre')
    plt.legend()
    plt.grid(True)
    plt.show()

    return model

# Ajustar modelos ARIMA para cada acción
arima_models = {}
for name in stocks:
    order = (2, 1, 2) if not stationarity_results[name] else (2, 0, 2)
    arima_models[name] = fit_arima_model(stocks[name]['Close'], name, order=order)

# Resumen de Hallazgos
print("\nResumen:")
print("1. Estacionariedad: Es probable que los precios de las acciones no sean estacionarios (basado en la prueba ADF). Se aplicó diferenciación cuando fue necesario.")
print("2. Cointegración: Se probaron todos los pares de acciones para determinar si están cointegradas (basado en el valor-p).")
print("3. Modelos: Se ajustaron modelos AR, ARMA y ARIMA para cada acción. Se generaron pronósticos para el próximo intervalo de 30 minutos.")
print("4. Visualizaciones: Las gráficas muestran las series originales, las series diferenciadas (si aplica) y los pronósticos para cada modelo.")