# -*- coding: utf-8 -*-
"""Microsoft vs. NU (5 Min)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkTyF8_n7SQRrDAW9w51hEu_qt0xbte_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller, coint
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.arima.model import ARIMA
from datetime import datetime, timedelta
from google.colab import files
import warnings
warnings.filterwarnings("ignore")

# Función para convertir fechas de Excel a datetime (si es numérico)
def excel_date_to_datetime(excel_date):
    if pd.api.types.is_numeric_dtype(excel_date):
        return pd.to_datetime('1899-12-30') + pd.to_timedelta(excel_date, unit='D')
    return excel_date  # Retorna tal cual si ya es datetime

# Solicitar la carga de archivos
print("Por favor, sube los archivos Excel de NU y Microsoft.")
uploaded = files.upload()

# Cargar datos desde los archivos subidos
try:
    # Buscar archivos, considerando posibles renombramientos por Colab
    nu_file = next((f for f in uploaded.keys() if 'NU' in f.upper()), None)
    microsoft_file = next((f for f in uploaded.keys() if 'MICROSOFT' in f.upper()), None)
    if not nu_file or not microsoft_file:
        raise ValueError("No se encontraron los archivos Excel de NU o Microsoft en los archivos subidos.")
    nu_df = pd.read_excel(nu_file)
    microsoft_df = pd.read_excel(microsoft_file)
except Exception as e:
    print(f"Error al cargar los archivos Excel: {e}")
    raise

# Imprimir nombres de columnas para depuración
print("Columnas del DataFrame de NU:", nu_df.columns.tolist())
print("Columnas del DataFrame de Microsoft:", microsoft_df.columns.tolist())

# Verificar columnas requeridas
required_columns = ['Date', 'Close']
for df, name in [(nu_df, 'NU'), (microsoft_df, 'Microsoft')]:
    if not all(col in df.columns for col in required_columns):
        raise KeyError(f"Faltan columnas requeridas en el DataFrame de {name}. Esperado: {required_columns}")

# Convertir fechas de Excel a datetime si es necesario
if not pd.api.types.is_datetime64_any_dtype(nu_df['Date']):
    nu_df['Date'] = excel_date_to_datetime(nu_df['Date'])
if not pd.api.types.is_datetime64_any_dtype(microsoft_df['Date']):
    microsoft_df['Date'] = excel_date_to_datetime(microsoft_df['Date'])

# Asegurar que Date sea datetime
nu_df['Date'] = pd.to_datetime(nu_df['Date'])
microsoft_df['Date'] = pd.to_datetime(microsoft_df['Date'])

# Establecer Date como índice y asegurar frecuencia de 5 minutos
nu_df.set_index('Date', inplace=True)
microsoft_df.set_index('Date', inplace=True)

# Manejar valores faltantes con forward fill
nu_df['Close'].fillna(method='ffill', inplace=True)
microsoft_df['Close'].fillna(method='ffill', inplace=True)

# Resample para asegurar frecuencia consistente de 5 minutos
nu_df = nu_df.resample('5T').ffill()
microsoft_df = microsoft_df.resample('5T').ffill()

# Alinear los DataFrames a su índice temporal común
common_index = nu_df.index.intersection(microsoft_df.index)
nu_df = nu_df.loc[common_index]
microsoft_df = microsoft_df.loc[common_index]

# Verificar longitudes después de la alineación
print(f"Longitud del DataFrame de NU: {len(nu_df)}")
print(f"Longitud del DataFrame de Microsoft: {len(microsoft_df)}")
if len(nu_df) != len(microsoft_df):
    raise ValueError("Los DataFrames tienen diferentes longitudes después de la alineación.")

# Graficar la serie temporal original
plt.figure(figsize=(12, 6))
plt.plot(nu_df['Close'], label='NU')
plt.plot(microsoft_df['Close'], label='Microsoft')
plt.title('Precios de Acciones de NU vs Microsoft (5-Minutos)')
plt.xlabel('Tiempo')
plt.ylabel('Precio de Cierre (USD)')
plt.legend()
plt.grid(True)
plt.show()

# Prueba de Estacionariedad (Prueba ADF)
def adf_test(series, name):
    result = adfuller(series.dropna())
    print(f'Prueba ADF para {name}:')
    print(f'Estadístico ADF: {result[0]}')
    print(f'valor-p: {result[1]}')
    print('Estacionario' if result[1] < 0.05 else 'No Estacionario')
    return result[1] < 0.05

# Realizar la prueba ADF en las series originales
nu_stationary = adf_test(nu_df['Close'], 'NU')
microsoft_stationary = adf_test(microsoft_df['Close'], 'Microsoft')

# Diferenciar si no es estacionario
nu_diff = nu_df['Close'].diff().dropna() if not nu_stationary else nu_df['Close']
microsoft_diff = microsoft_df['Close'].diff().dropna() if not microsoft_stationary else microsoft_df['Close']

# Graficar la serie diferenciada si se aplicó
if not nu_stationary or not microsoft_stationary:
    plt.figure(figsize=(12, 6))
    plt.plot(nu_diff, label='NU Diferenciada')
    plt.plot(microsoft_diff, label='Microsoft Diferenciada')
    plt.title('Precios de Acciones Diferenciados (5-Minutos)')
    plt.xlabel('Tiempo')
    plt.ylabel('Diferencia de Precio')
    plt.legend()
    plt.grid(True)
    plt.show()

# Volver a probar la estacionariedad en las series diferenciadas
if not nu_stationary:
    adf_test(nu_diff, 'NU Diferenciada')
if not microsoft_stationary:
    adf_test(microsoft_diff, 'Microsoft Diferenciada')

# Prueba de Cointegración
score, p_value, _ = coint(nu_df['Close'], microsoft_df['Close'])
print(f'Prueba de Cointegración:')
print(f'valor-p: {p_value}')
print('Cointegradas' if p_value < 0.05 else 'No Cointegradas')

# Modelo AR
def fit_ar_model(series, name, lags=5):
    model = AutoReg(series, lags=lags).fit()
    print(f'Modelo AR({lags}) para {name}:')
    print(model.summary())

    # Pronóstico
    forecast = model.predict(start=len(series), end=len(series)+1)  # 10 minutos = 2 pasos a 5-min de frecuencia

    # Gráfico
    plt.figure(figsize=(12, 6))
    plt.plot(series[-50:], label='Actual')
    forecast_index = pd.date_range(start=series.index[-1] + timedelta(minutes=5), periods=2, freq='5T')
    plt.plot(forecast_index, forecast, label='Pronóstico', linestyle='--')
    plt.title(f'Pronóstico AR({lags}) para {name} (10-Minutos Adelante)')
    plt.xlabel('Tiempo')
    plt.ylabel('Precio de Cierre')
    plt.legend()
    plt.grid(True)
    plt.show()

    return model

# Ajustar modelos AR
nu_ar = fit_ar_model(nu_diff, 'NU')
microsoft_ar = fit_ar_model(microsoft_diff, 'Microsoft')

# Modelo ARMA (asumiendo ARMA(2,2))
def fit_arma_model(series, name, order=(2,2)):
    model = ARIMA(series, order=(order[0], 0, order[1])).fit()
    print(f'Modelo ARMA({order[0]},{order[1]}) para {name}:')
    print(model.summary())

    # Pronóstico
    forecast = model.forecast(steps=2)  # 10 minutos = 2 pasos a 5-min de frecuencia

    # Gráfico
    plt.figure(figsize=(12, 6))
    plt.plot(series[-50:], label='Actual')
    forecast_index = pd.date_range(start=series.index[-1] + timedelta(minutes=5), periods=2, freq='5T')
    plt.plot(forecast_index, forecast, label='Pronóstico', linestyle='--')
    plt.title(f'Pronóstico ARMA({order[0]},{order[1]}) para {name} (10-Minutos Adelante)')
    plt.xlabel('Tiempo')
    plt.ylabel('Precio de Cierre')
    plt.legend()
    plt.grid(True)
    plt.show()

    return model

# Ajustar modelos ARMA
nu_arma = fit_arma_model(nu_diff, 'NU')
microsoft_arma = fit_arma_model(microsoft_diff, 'Microsoft')

# Modelo ARIMA (asumiendo ARIMA(2,1,2) si no es estacionario, sino ARIMA(2,0,2))
def fit_arima_model(series, name, order=(2,1,2)):
    model = ARIMA(series, order=order).fit()
    print(f'Modelo ARIMA({order[0]},{order[1]},{order[2]}) para {name}:')
    print(model.summary())

    # Pronóstico
    forecast = model.forecast(steps=2)  # 10 minutos = 2 pasos a 5-min de frecuencia

    # Gráfico
    plt.figure(figsize=(12, 6))
    plt.plot(series[-50:], label='Actual')
    forecast_index = pd.date_range(start=series.index[-1] + timedelta(minutes=5), periods=2, freq='5T')
    plt.plot(forecast_index, forecast, label='Pronóstico', linestyle='--')
    plt.title(f'Pronóstico ARIMA({order[0]},{order[1]},{order[2]}) para {name} (10-Minutos Adelante)')
    plt.xlabel('Tiempo')
    plt.ylabel('Precio de Cierre')
    plt.legend()
    plt.grid(True)
    plt.show()

    return model

# Ajustar modelos ARIMA (usar datos diferenciados si no es estacionario)
nu_arima = fit_arima_model(nu_df['Close'], 'NU', order=(2,1,2) if not nu_stationary else (2,0,2))
microsoft_arima = fit_arima_model(microsoft_df['Close'], 'Microsoft', order=(2,1,2) if not microsoft_stationary else (2,0,2))

# Resumen de Hallazgos
print("\nResumen:")
print("1. Estacionariedad: Es probable que los precios de NU y Microsoft no sean estacionarios (basado en la prueba ADF). Se aplicó diferenciación cuando fue necesario.")
print("2. Cointegración: Las acciones pueden o no estar cointegradas (basado en el valor-p).")
print("3. Modelos: Se ajustaron modelos AR, ARMA y ARIMA. Se generaron pronósticos para los próximos 10 minutos.")
print("4. Visualizaciones: Las gráficas muestran la serie original, la serie diferenciada (si aplica) y los pronósticos para cada modelo.")