# -*- coding: utf-8 -*-
"""Pregunta 19 Examen Series de Tiempo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEJzPV94qwcUnyrrs3KpvhqoV4AOK00E
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np
from google.colab import files
from statsmodels.tsa.stattools import adfuller, coint
from statsmodels.tsa.vector_ar.var_model import VAR
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# Step 1: Data Preparation
# Upload the text file
print("Please upload the text file (e.g., Table 22.7 (1).txt)")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Read the text file with flexible parsing
# Try tab separator, skip header rows, and handle potential extra columns
df = pd.read_csv(filename, sep='\s+', skiprows=8, skipfooter=20, engine='python')

# Debug: Print raw columns to diagnose issue
print("\nRaw DataFrame Columns:", df.columns.tolist())
print("First few rows:\n", df.head())

# Attempt to assign expected columns, adjusting for actual structure
# Assuming columns are 'obs', 'GS3M', 'GS6M' based on document
if len(df.columns) >= 3:
    df = df.iloc[:, :3]  # Take first three columns
    df.columns = ['obs', 'GS3M', 'GS6M']
else:
    raise ValueError("Unexpected number of columns in data. Expected at least 3.")

# Extract GS3M and GS6M, convert to float
tb3m = df['GS3M'].astype(float)
tb6m = df['GS6M'].astype(float)
time = pd.date_range(start='1982-01-01', periods=len(df), freq='M')

# Data validation
print("\nData Validation:")
print(f"Length: {len(tb3m)} observations")
print(f"GS3M NaN count: {tb3m.isna().sum()}")
print(f"GS6M NaN count: {tb6m.isna().sum()}")
print(f"GS3M Infinite values: {np.isinf(tb3m).sum()}")
print(f"GS6M Infinite values: {np.isinf(tb6m).sum()}")

# Part a: Plot both time series
plt.figure(figsize=(10, 6))
plt.plot(time, tb3m, label='3-Month Treasury Bill Rate (GS3M)', color='blue')
plt.plot(time, tb6m, label='6-Month Treasury Bill Rate (GS6M)', color='red')
plt.title('Three-Month and Six-Month Treasury Bill Rates (Jan 1982 - Jun 2001)')
plt.xlabel('Date')
plt.ylabel('Interest Rate (%)')
plt.legend()
plt.savefig('tb_rates_plot.png')
plt.show()

# Part b: Unit Root Analysis
def adf_test(series, name):
    print(f"\nADF Test for {name}:")
    result = adfuller(series)
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print(f'Critical Values: {result[4]}')
    if result[1] < 0.05:
        print("Result: Stationary (reject null)")
    else:
        print("Result: Non-stationary (fail to reject null)")
    return result[1]

# ADF tests for GS3M and GS6M
tb3m_pvalue = adf_test(tb3m, "GS3M")
tb6m_pvalue = adf_test(tb6m, "GS6M")

# ADF tests for first differences if non-stationary
if tb3m_pvalue >= 0.05:
    print("\nADF Test for First Difference of GS3M:")
    adf_test(tb3m.diff().dropna(), "Differenced GS3M")
if tb6m_pvalue >= 0.05:
    print("\nADF Test for First Difference of GS6M:")
    adf_test(tb6m.diff().dropna(), "Differenced GS6M")

# Part c: Cointegration Test
print("\nCointegration Test (Engle-Granger) between GS3M and GS6M:")
try:
    score, p_value, _ = coint(tb3m, tb6m)
    print(f'Cointegration test statistic: {score:.4f}')
    print(f'p-value: {p_value:.4f}')
    if p_value < 0.05:
        print("Result: GS3M and GS6M are cointegrated.")
    else:
        print("Result: GS3M and GS6M are not cointegrated.")
except Exception as e:
    print(f"Error in cointegration test: {e}")

# Part d: Economic Interpretation (Printed below after results)

# Part e: VAR Model Analysis
# Prepare data for VAR
data = pd.DataFrame({'GS3M': tb3m, 'GS6M': tb6m}, index=time)
data_diff = data.diff().dropna()

# Fit VAR(4) model on levels
print("\nFitting VAR(4) model on levels...")
try:
    model_levels = VAR(data).fit(maxlags=4)
    print(model_levels.summary())
except Exception as e:
    print(f"Error fitting VAR on levels: {e}")

# Fit VAR(4) model on first differences
print("\nFitting VAR(4) model on first differences...")
try:
    model_diff = VAR(data_diff).fit(maxlags=4)
    print(model_diff.summary())
except Exception as e:
    print(f"Error fitting VAR on differences: {e}")

# Part d and e: Interpretations
print("\nPart d: Economic Meaning of Cointegration")
print("If GS3M and GS6M are cointegrated, there is a stable long-run relationship between the two Treasury bill rates, driven by common factors like monetary policy. The spread (GS6M - GS3M) remains stable, enabling forecasting or arbitrage strategies. If not cointegrated, the rates drift apart, implying independent short-term movements, which complicates yield curve analysis and policy modeling.")
print("\nPart e: VAR Model Choice")
print("If both series are non-stationary (ADF p-value ≥ 0.05) and not cointegrated, use first differences for the VAR(4) model to ensure stationarity and avoid spurious regression. If cointegrated, a Vector Error Correction Model (VECM) is preferred, but levels can be used cautiously in VAR. Based on the data, check cointegration results to decide; differencing is safer if cointegration is absent.")