# -*- coding: utf-8 -*-
"""Pregunta 19 Examen Series de Tiempo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEJzPV94qwcUnyrrs3KpvhqoV4AOK00E
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np
from google.colab import files
from statsmodels.tsa.stattools import adfuller, coint
from statsmodels.tsa.vector_ar.var_model import VAR
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# Step 1: Data Preparation
# Upload the Excel file
print("Please upload the Excel file (e.g., Macroeconomic_Data_USA.xlsx)")
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_excel(filename)

# Extract PROFITS (proxy for TB3M) and DIVIDENDS (proxy for TB6M)
tb3m = df['PROFITS']
tb6m = df['DIVIDENDS']
time = df['YEAR']

# Data validation
print("\nData Validation:")
print(f"Length: {len(tb3m)} observations")
print(f"TB3M (PROFITS) NaN count: {tb3m.isna().sum()}")
print(f"TB6M (DIVIDENDS) NaN count: {tb6m.isna().sum()}")
print(f"TB3M Infinite values: {np.isinf(tb3m).sum()}")
print(f"TB6M Infinite values: {np.isinf(tb6m).sum()}")

# Part a: Plot both time series
plt.figure(figsize=(10, 6))
plt.plot(time, tb3m, label='TB3M (Proxy: PROFITS)', color='blue')
plt.plot(time, tb6m, label='TB6M (Proxy: DIVIDENDS)', color='red')
plt.title('Three-Month and Six-Month Treasury Bill Rates (Proxies)')
plt.xlabel('Year')
plt.ylabel('Value')
plt.legend()
plt.savefig('tb_rates_plot.png')
plt.show()

# Part b: Unit Root Analysis
def adf_test(series, name):
    print(f"\nADF Test for {name}:")
    result = adfuller(series)
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print(f'Critical Values: {result[4]}')
    if result[1] < 0.05:
        print("Result: Stationary (reject null)")
    else:
        print("Result: Non-stationary (fail to reject null)")
    return result[1]

# ADF tests for TB3M and TB6M
tb3m_pvalue = adf_test(tb3m, "TB3M (PROFITS)")
tb6m_pvalue = adf_test(tb6m, "TB6M (DIVIDENDS)")

# ADF tests for first differences if non-stationary
if tb3m_pvalue >= 0.05:
    print("\nADF Test for First Difference of TB3M:")
    adf_test(tb3m.diff().dropna(), "Differenced TB3M")
if tb6m_pvalue >= 0.05:
    print("\nADF Test for First Difference of TB6M:")
    adf_test(tb6m.diff().dropna(), "Differenced TB6M")

# Part c: Cointegration Test
print("\nCointegration Test (Engle-Granger) between TB3M and TB6M:")
try:
    score, p_value, _ = coint(tb3m, tb6m)
    print(f'Cointegration test statistic: {score:.4f}')
    print(f'p-value: {p_value:.4f}')
    if p_value < 0.05:
        print("Result: TB3M and TB6M are cointegrated.")
    else:
        print("Result: TB3M and TB6M are not cointegrated.")
except Exception as e:
    print(f"Error in cointegration test: {e}")

# Part d: Economic Interpretation (Printed below after results)

# Part e: VAR Model Analysis
# Prepare data for VAR
data = pd.DataFrame({'TB3M': tb3m, 'TB6M': tb6m})
data_diff = data.diff().dropna()

# Fit VAR(4) model on levels
print("\nFitting VAR(4) model on levels...")
try:
    model_levels = VAR(data).fit(maxlags=4)
    print(model_levels.summary())
except Exception as e:
    print(f"Error fitting VAR on levels: {e}")

# Fit VAR(4) model on first differences
print("\nFitting VAR(4) model on first differences...")
try:
    model_diff = VAR(data_diff).fit(maxlags=4)
    print(model_diff.summary())
except Exception as e:
    print(f"Error fitting VAR on differences: {e}")

# Part d and e: Interpretations
print("\nPart d: Economic Meaning of Cointegration")
print("If TB3M and TB6M are cointegrated, there exists a stable long-run relationship between the two Treasury bill rates, likely due to shared economic factors like monetary policy. For example, the spread (TB6M - TB3M) remains stable over time, useful for forecasting or arbitrage strategies. If not cointegrated (as likely with PROFITS and DIVIDENDS), the series drift apart, implying independent movements and no reliable long-term relationship, complicating joint forecasting or policy analysis.")
print("\nPart e: VAR Model Choice")
print("If both series are non-stationary (ADF p-value ≥ 0.05) and not cointegrated, use first differences for the VAR(4) model to ensure stationarity and avoid spurious regression. If cointegrated, a Vector Error Correction Model (VECM) is preferred, but levels can be used cautiously in VAR if cointegration is strong. Given the proxy data (PROFITS and DIVIDENDS), differencing is likely necessary due to non-stationarity and lack of cointegration.")