# -*- coding: utf-8 -*-
"""Problema Examen 18 Series de Tiempo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KgmH_wZ-_XSly-wQ4us3-RypxU5mOw8a
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np
from google.colab import files
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.stats.diagnostic import acorr_ljungbox
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# Step 1: Data Preparation
# Upload the Excel file (using M1 as a proxy for DPI)
print("Please upload the Excel file (e.g., 21.1.xlsx)")
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_excel(filename)

# Extract the MONEY column and apply log transformation
log_dpi = np.log(df['MONEY'])
time = df['TIME']

# Plot the log DPI series
plt.figure(figsize=(10, 6))
plt.plot(time, log_dpi, label='Log DPI (M1 Proxy)')
plt.title('Log of Disposable Personal Income (Proxy: M1 Money Supply)')
plt.xlabel('Time (1 = Jan 1951, 489 = Sep 1991)')
plt.ylabel('Log DPI')
plt.legend()
plt.savefig('log_dpi_plot.png')
plt.show()

# Data validation
print("\nData Validation:")
print(f"Length: {len(log_dpi)}")
print(f"NaN count: {log_dpi.isna().sum()}")
print(f"Infinite values: {np.isinf(log_dpi).sum()}")

# Step 2: Test for Stationarity
def adf_test(series, name):
    print(f"\nADF Test for {name}:")
    result = adfuller(series)
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print(f'Critical Values: {result[4]}')
    if result[1] < 0.05:
        print("Result: Stationary (reject null)")
    else:
        print("Result: Non-stationary (fail to reject null)")
    return result[1]

# Test original log DPI
adf_pvalue = adf_test(log_dpi, "Log DPI")

# Differencing if non-stationary
d = 0
diff_series = log_dpi
if adf_pvalue >= 0.05:
    print("\nDifferencing the series...")
    diff_series = log_dpi.diff().dropna()
    d = 1
    adf_pvalue = adf_test(diff_series, "Differenced Log DPI")
    if adf_pvalue >= 0.05:
        diff_series = diff_series.diff().dropna()
        d = 2
        adf_pvalue = adf_test(diff_series, "Twice-Differenced Log DPI")

# Plot differenced series
plt.figure(figsize=(10, 6))
plt.plot(diff_series, label=f'Differenced Log DPI (d={d})')
plt.title(f'Differenced Log DPI (d={d})')
plt.xlabel('Time')
plt.ylabel('Differenced Log DPI')
plt.legend()
plt.savefig('diff_log_dpi_plot.png')
plt.show()

# Step 3: Identify ARIMA Model Orders
# Plot ACF and PACF of the stationary series
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plot_acf(diff_series, lags=20, ax=plt.gca())
plt.title('ACF of Differenced Log DPI')
plt.subplot(1, 2, 2)
plot_pacf(diff_series, lags=20, ax=plt.gca())
plt.title('PACF of Differenced Log DPI')
plt.tight_layout()
plt.savefig('acf_pacf_plot.png')
plt.show()

# Step 4: Estimate ARIMA Models
def find_best_arima(series, max_p=2, max_q=2):
    print("\nFitting ARIMA models...")
    best_aic = float('inf')
    best_order = None
    for p in range(max_p + 1):
        for q in range(max_q + 1):
            try:
                model = ARIMA(log_dpi, order=(p, d, q))
                results = model.fit()
                if results.aic < best_aic:
                    best_aic = results.aic
                    best_order = (p, d, q)
            except Exception as e:
                print(f"Failed ARIMA({p},{d},{q}): {e}")
                continue
    if best_order is None:
        print("Error: No valid ARIMA model found.")
        return None
    print(f"\nBest ARIMA model: Order {best_order}, AIC: {best_aic:.2f}")
    return best_order

# Fit the best ARIMA model
best_order = find_best_arima(log_dpi)
if best_order is None:
    raise Exception("Cannot proceed without a valid ARIMA model.")

# Fit the final model
model = ARIMA(log_dpi, order=best_order).fit()
print(model.summary())

# Step 5: Diagnostic Checking
# Plot residuals
residuals = model.resid
plt.figure(figsize=(10, 6))
plt.plot(residuals, label='Residuals')
plt.axhline(0, color='black', linestyle='--', alpha=0.5)
plt.title('Residuals of ARIMA Model')
plt.legend()
plt.savefig('residuals_plot.png')
plt.show()

# ACF of residuals
plt.figure(figsize=(10, 4))
plot_acf(residuals, lags=20, ax=plt.gca())
plt.title('ACF of Residuals')
plt.savefig('residuals_acf_plot.png')
plt.show()

# Ljung-Box test
lb_test = acorr_ljungbox(residuals, lags=[10], return_df=True)
print("\nLjung-Box Test for Residual Autocorrelation:")
print(lb_test)
if lb_test['lb_pvalue'].iloc[0] > 0.05:
    print("Result: Residuals are white noise (no autocorrelation).")
else:
    print("Result: Residuals show autocorrelation. Consider refining the model.")

# Step 6: Forecasting
forecast_steps = 12
forecast = model.get_forecast(steps=forecast_steps)
forecast_mean = forecast.predicted_mean
forecast_ci = forecast.conf_int()

# Plot forecast
plt.figure(figsize=(10, 6))
plt.plot(log_dpi[-50:], label='Historical Log DPI')
plt.plot(range(len(log_dpi), len(log_dpi) + forecast_steps), forecast_mean, label='Forecast', color='red')
plt.fill_between(range(len(log_dpi), len(log_dpi) + forecast_steps),
                 forecast_ci.iloc[:, 0], forecast_ci.iloc[:, 1],
                 color='pink', alpha=0.3, label='95% Confidence Interval')
plt.title('Log DPI Forecast (12 Months)')
plt.xlabel('Time')
plt.ylabel('Log DPI')
plt.legend()
plt.savefig('forecast_plot.png')
plt.show()

# Print forecast values
print("\nForecasted Log DPI for Next 12 Months:")
print(forecast_mean)