# -*- coding: utf-8 -*-
"""Robinhood vs GM (30 min)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_Zf8NwzcQNRNfwdcVK7kU1azrlf1oVy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller, coint
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.arima.model import ARIMA
from datetime import datetime, timedelta
from google.colab import files
import warnings
warnings.filterwarnings("ignore")

# Función para convertir fechas de Excel a datetime (si es numérico)
def excel_date_to_datetime(excel_date):
    if pd.api.types.is_numeric_dtype(excel_date):
        return pd.to_datetime('1899-12-30') + pd.to_timedelta(excel_date, unit='D')
    return excel_date  # Retorna tal cual si ya es datetime

# Solicitar la carga de archivos
print("Por favor, sube los archivos Excel de Robinhood y General Motors.")
uploaded = files.upload()

# Cargar datos desde los archivos subidos
try:
    # Buscar archivos, considerando posibles renombramientos por Colab
    robinhood_file = next((f for f in uploaded.keys() if 'ROBINHOOD' in f.upper()), None)
    gm_file = next((f for f in uploaded.keys() if 'GENERAL MOTOR' in f.upper() or 'GM' in f.upper()), None)
    if not robinhood_file or not gm_file:
        raise ValueError("No se encontraron los archivos Excel de Robinhood o General Motors en los archivos subidos.")
    robinhood_df = pd.read_excel(robinhood_file)
    gm_df = pd.read_excel(gm_file)
except Exception as e:
    print(f"Error al cargar los archivos Excel: {e}")
    raise

# Imprimir nombres de columnas para depuración
print("Columnas del DataFrame de Robinhood:", robinhood_df.columns.tolist())
print("Columnas del DataFrame de General Motors:", gm_df.columns.tolist())

# Verificar columnas requeridas
required_columns = ['Date', 'Close']
for df, name in [(robinhood_df, 'Robinhood'), (gm_df, 'General Motors')]:
    if not all(col in df.columns for col in required_columns):
        raise KeyError(f"Faltan columnas requeridas en el DataFrame de {name}. Esperado: {required_columns}")

# Convertir fechas de Excel a datetime si es necesario
if not pd.api.types.is_datetime64_any_dtype(robinhood_df['Date']):
    robinhood_df['Date'] = excel_date_to_datetime(robinhood_df['Date'])
if not pd.api.types.is_datetime64_any_dtype(gm_df['Date']):
    gm_df['Date'] = excel_date_to_datetime(gm_df['Date'])

# Asegurar que Date sea datetime
robinhood_df['Date'] = pd.to_datetime(robinhood_df['Date'])
gm_df['Date'] = pd.to_datetime(gm_df['Date'])

# Establecer Date como índice y asegurar frecuencia de 30 minutos
robinhood_df.set_index('Date', inplace=True)
gm_df.set_index('Date', inplace=True)

# Manejar valores faltantes con forward fill
robinhood_df['Close'].fillna(method='ffill', inplace=True)
gm_df['Close'].fillna(method='ffill', inplace=True)

# Resample para asegurar frecuencia consistente de 30 minutos
robinhood_df = robinhood_df.resample('30T').ffill()
gm_df = gm_df.resample('30T').ffill()

# Alinear los DataFrames a su índice temporal común
common_index = robinhood_df.index.intersection(gm_df.index)
robinhood_df = robinhood_df.loc[common_index]
gm_df = gm_df.loc[common_index]

# Verificar longitudes después de la alineación
print(f"Longitud del DataFrame de Robinhood: {len(robinhood_df)}")
print(f"Longitud del DataFrame de General Motors: {len(gm_df)}")
if len(robinhood_df) != len(gm_df):
    raise ValueError("Los DataFrames tienen diferentes longitudes después de la alineación.")

# Graficar la serie temporal original
plt.figure(figsize=(12, 6))
plt.plot(robinhood_df['Close'], label='Robinhood')
plt.plot(gm_df['Close'], label='General Motors')
plt.title('Precios de Acciones de Robinhood vs General Motors (30-Minutos)')
plt.xlabel('Tiempo')
plt.ylabel('Precio de Cierre (USD)')
plt.legend()
plt.grid(True)
plt.show()

# Prueba de Estacionariedad (Prueba ADF)
def adf_test(series, name):
    result = adfuller(series.dropna())
    print(f'Prueba ADF para {name}:')
    print(f'Estadístico ADF: {result[0]}')
    print(f'valor-p: {result[1]}')
    print('Estacionario' if result[1] < 0.05 else 'No Estacionario')
    return result[1] < 0.05

# Realizar la prueba ADF en las series originales
robinhood_stationary = adf_test(robinhood_df['Close'], 'Robinhood')
gm_stationary = adf_test(gm_df['Close'], 'General Motors')

# Diferenciar si no es estacionario
robinhood_diff = robinhood_df['Close'].diff().dropna() if not robinhood_stationary else robinhood_df['Close']
gm_diff = gm_df['Close'].diff().dropna() if not gm_stationary else gm_df['Close']

# Graficar la serie diferenciada si se aplicó
if not robinhood_stationary or not gm_stationary:
    plt.figure(figsize=(12, 6))
    plt.plot(robinhood_diff, label='Robinhood Diferenciada')
    plt.plot(gm_diff, label='General Motors Diferenciada')
    plt.title('Precios de Acciones Diferenciados (30-Minutos)')
    plt.xlabel('Tiempo')
    plt.ylabel('Diferencia de Precio')
    plt.legend()
    plt.grid(True)
    plt.show()

# Volver a probar la estacionariedad en las series diferenciadas
if not robinhood_stationary:
    adf_test(robinhood_diff, 'Robinhood Diferenciada')
if not gm_stationary:
    adf_test(gm_diff, 'General Motors Diferenciada')

# Prueba de Cointegración
score, p_value, _ = coint(robinhood_df['Close'], gm_df['Close'])
print(f'Prueba de Cointegración:')
print(f'valor-p: {p_value}')
print('Cointegradas' if p_value < 0.05 else 'No Cointegradas')

# Modelo AR
def fit_ar_model(series, name, lags=5):
    model = AutoReg(series, lags=lags).fit()
    print(f'Modelo AR({lags}) para {name}:')
    print(model.summary())

    # Pronóstico: 10 minutos es menos de 30 minutos, así que pronosticamos 1 paso (próximo intervalo de 30 minutos)
    forecast = model.predict(start=len(series), end=len(series))  # 1 paso a 30-min de frecuencia

    # Gráfico
    plt.figure(figsize=(12, 6))
    plt.plot(series[-50:], label='Actual')
    forecast_index = pd.date_range(start=series.index[-1] + timedelta(minutes=30), periods=1, freq='30T')
    plt.plot(forecast_index, forecast, label='Pronóstico', linestyle='--')
    plt.title(f'Pronóstico AR({lags}) para {name} (Próximo Intervalo de 30 Minutos)')
    plt.xlabel('Tiempo')
    plt.ylabel('Precio de Cierre')
    plt.legend()
    plt.grid(True)
    plt.show()

    return model

# Ajustar modelos AR
robinhood_ar = fit_ar_model(robinhood_diff, 'Robinhood')
gm_ar = fit_ar_model(gm_diff, 'General Motors')

# Modelo ARMA (asumiendo ARMA(2,2))
def fit_arma_model(series, name, order=(2,2)):
    model = ARIMA(series, order=(order[0], 0, order[1])).fit()
    print(f'Modelo ARMA({order[0]},{order[1]}) para {name}:')
    print(model.summary())

    # Pronóstico: 1 paso a 30-min de frecuencia
    forecast = model.forecast(steps=1)

    # Gráfico
    plt.figure(figsize=(12, 6))
    plt.plot(series[-50:], label='Actual')
    forecast_index = pd.date_range(start=series.index[-1] + timedelta(minutes=30), periods=1, freq='30T')
    plt.plot(forecast_index, forecast, label='Pronóstico', linestyle='--')
    plt.title(f'Pronóstico ARMA({order[0]},{order[1]}) para {name} (Próximo Intervalo de 30 Minutos)')
    plt.xlabel('Tiempo')
    plt.ylabel('Precio de Cierre')
    plt.legend()
    plt.grid(True)
    plt.show()

    return model

# Ajustar modelos ARMA
robinhood_arma = fit_arma_model(robinhood_diff, 'Robinhood')
gm_arma = fit_arma_model(gm_diff, 'General Motors')

# Modelo ARIMA (asumiendo ARIMA(2,1,2) si no es estacionario, sino ARIMA(2,0,2))
def fit_arima_model(series, name, order=(2,1,2)):
    model = ARIMA(series, order=order).fit()
    print(f'Modelo ARIMA({order[0]},{order[1]},{order[2]}) para {name}:')
    print(model.summary())

    # Pronóstico: 1 paso a 30-min de frecuencia
    forecast = model.forecast(steps=1)

    # Gráfico
    plt.figure(figsize=(12, 6))
    plt.plot(series[-50:], label='Actual')
    forecast_index = pd.date_range(start=series.index[-1] + timedelta(minutes=30), periods=1, freq='30T')
    plt.plot(forecast_index, forecast, label='Pronóstico', linestyle='--')
    plt.title(f'Pronóstico ARIMA({order[0]},{order[1]},{order[2]}) para {name} (Próximo Intervalo de 30 Minutos)')
    plt.xlabel('Tiempo')
    plt.ylabel('Precio de Cierre')
    plt.legend()
    plt.grid(True)
    plt.show()

    return model

# Ajustar modelos ARIMA (usar datos diferenciados si no es estacionario)
robinhood_arima = fit_arima_model(robinhood_df['Close'], 'Robinhood', order=(2,1,2) if not robinhood_stationary else (2,0,2))
gm_arima = fit_arima_model(gm_df['Close'], 'General Motors', order=(2,1,2) if not gm_stationary else (2,0,2))

# Resumen de Hallazgos
print("\nResumen:")
print("1. Estacionariedad: Es probable que los precios de Robinhood y General Motors no sean estacionarios (basado en la prueba ADF). Se aplicó diferenciación cuando fue necesario.")
print("2. Cointegración: Las acciones pueden o no estar cointegradas (basado en el valor-p).")
print("3. Modelos: Se ajustaron modelos AR, ARMA y ARIMA. Se generaron pronósticos para el próximo intervalo de 30 minutos.")
print("4. Visualizaciones: Las gráficas muestran la serie original, la serie diferenciada (si aplica) y los pronósticos para cada modelo.")