# -*- coding: utf-8 -*-
"""Robinhood vs General Motors (5 MIN)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_hqS2T2GJy0JnhnxLJnUMnCBLoQbGTu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller, coint
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.arima.model import ARIMA
from datetime import datetime, timedelta
from google.colab import files
import warnings
warnings.filterwarnings("ignore")

# Function to convert Excel date to datetime (if numeric)
def excel_date_to_datetime(excel_date):
    if pd.api.types.is_numeric_dtype(excel_date):
        return pd.to_datetime('1899-12-30') + pd.to_timedelta(excel_date, unit='D')
    return excel_date  # Return as-is if already datetime

# Prompt user to upload files
print("Please upload the Robinhood and General Motors Excel files.")
uploaded = files.upload()

# Load data from uploaded files
try:
    # Load files, accounting for possible renaming by Colab
    robinhood_file = next((f for f in uploaded.keys() if 'ROBINHOOD' in f.upper()), None)
    gm_file = next((f for f in uploaded.keys() if 'GENERAL MOTOR' in f.upper() or 'GM' in f.upper()), None)
    if not robinhood_file or not gm_file:
        raise ValueError("Could not find Robinhood or General Motors Excel files in uploaded files.")
    robinhood_df = pd.read_excel(robinhood_file)
    gm_df = pd.read_excel(gm_file)
except Exception as e:
    print(f"Error loading Excel files: {e}")
    raise

# Print column names for debugging
print("Robinhood DataFrame columns:", robinhood_df.columns.tolist())
print("General Motors DataFrame columns:", gm_df.columns.tolist())

# Check for required columns
required_columns = ['Date', 'Close']
for df, name in [(robinhood_df, 'Robinhood'), (gm_df, 'General Motors')]:
    if not all(col in df.columns for col in required_columns):
        raise KeyError(f"Missing required columns in {name} DataFrame. Expected: {required_columns}")

# Convert Excel dates to datetime if necessary
if not pd.api.types.is_datetime64_any_dtype(robinhood_df['Date']):
    robinhood_df['Date'] = excel_date_to_datetime(robinhood_df['Date'])
if not pd.api.types.is_datetime64_any_dtype(gm_df['Date']):
    gm_df['Date'] = excel_date_to_datetime(gm_df['Date'])

# Ensure Date is datetime
robinhood_df['Date'] = pd.to_datetime(robinhood_df['Date'])
gm_df['Date'] = pd.to_datetime(gm_df['Date'])

# Set Date as index and ensure 5-minute frequency
robinhood_df.set_index('Date', inplace=True)
gm_df.set_index('Date', inplace=True)

# Handle missing values by forward fill
robinhood_df['Close'].fillna(method='ffill', inplace=True)
gm_df['Close'].fillna(method='ffill', inplace=True)

# Resample to ensure consistent 5-minute frequency
robinhood_df = robinhood_df.resample('5T').ffill()
gm_df = gm_df.resample('5T').ffill()

# Align the DataFrames to their common time index
common_index = robinhood_df.index.intersection(gm_df.index)
robinhood_df = robinhood_df.loc[common_index]
gm_df = gm_df.loc[common_index]

# Verify lengths after alignment
print(f"Robinhood DataFrame length: {len(robinhood_df)}")
print(f"General Motors DataFrame length: {len(gm_df)}")
if len(robinhood_df) != len(gm_df):
    raise ValueError("DataFrames have different lengths after alignment.")

# Plot original time series
plt.figure(figsize=(12, 6))
plt.plot(robinhood_df['Close'], label='Robinhood')
plt.plot(gm_df['Close'], label='General Motors')
plt.title('Robinhood vs General Motors Stock Prices (5-Minute)')
plt.xlabel('Time')
plt.ylabel('Close Price (USD)')
plt.legend()
plt.grid(True)
plt.show()

# Stationarity Test (ADF Test)
def adf_test(series, name):
    result = adfuller(series.dropna())
    print(f'ADF Test for {name}:')
    print(f'ADF Statistic: {result[0]}')
    print(f'p-value: {result[1]}')
    print('Stationary' if result[1] < 0.05 else 'Non-Stationary')
    return result[1] < 0.05

# Perform ADF test on original series
robinhood_stationary = adf_test(robinhood_df['Close'], 'Robinhood')
gm_stationary = adf_test(gm_df['Close'], 'General Motors')

# Differencing if non-stationary
robinhood_diff = robinhood_df['Close'].diff().dropna() if not robinhood_stationary else robinhood_df['Close']
gm_diff = gm_df['Close'].diff().dropna() if not gm_stationary else gm_df['Close']

# Plot differenced series if applied
if not robinhood_stationary or not gm_stationary:
    plt.figure(figsize=(12, 6))
    plt.plot(robinhood_diff, label='Robinhood Differenced')
    plt.plot(gm_diff, label='General Motors Differenced')
    plt.title('Differenced Stock Prices (5-Minute)')
    plt.xlabel('Time')
    plt.ylabel('Price Difference')
    plt.legend()
    plt.grid(True)
    plt.show()

# Re-test stationarity on differenced series
if not robinhood_stationary:
    adf_test(robinhood_diff, 'Robinhood Differenced')
if not gm_stationary:
    adf_test(gm_diff, 'General Motors Differenced')

# Cointegration Test
score, p_value, _ = coint(robinhood_df['Close'], gm_df['Close'])
print(f'Cointegration Test:')
print(f'p-value: {p_value}')
print('Cointegrated' if p_value < 0.05 else 'Not Cointegrated')

# AR Model
def fit_ar_model(series, name, lags=5):
    model = AutoReg(series, lags=lags).fit()
    print(f'AR({lags}) Model for {name}:')
    print(model.summary())

    # Forecast
    forecast = model.predict(start=len(series), end=len(series)+1)  # 10 minutes = 2 steps at 5-min frequency

    # Plot
    plt.figure(figsize=(12, 6))
    plt.plot(series[-50:], label='Actual')
    forecast_index = pd.date_range(start=series.index[-1] + timedelta(minutes=5), periods=2, freq='5T')
    plt.plot(forecast_index, forecast, label='Forecast', linestyle='--')
    plt.title(f'AR({lags}) Forecast for {name} (10-Minute Ahead)')
    plt.xlabel('Time')
    plt.ylabel('Close Price')
    plt.legend()
    plt.grid(True)
    plt.show()

    return model

# Fit AR models
robinhood_ar = fit_ar_model(robinhood_diff, 'Robinhood')
gm_ar = fit_ar_model(gm_diff, 'General Motors')

# ARMA Model (assuming ARMA(2,2))
def fit_arma_model(series, name, order=(2,2)):
    model = ARIMA(series, order=(order[0], 0, order[1])).fit()
    print(f'ARMA({order[0]},{order[1]}) Model for {name}:')
    print(model.summary())

    # Forecast
    forecast = model.forecast(steps=2)  # 10 minutes = 2 steps at 5-min frequency

    # Plot
    plt.figure(figsize=(12, 6))
    plt.plot(series[-50:], label='Actual')
    forecast_index = pd.date_range(start=series.index[-1] + timedelta(minutes=5), periods=2, freq='5T')
    plt.plot(forecast_index, forecast, label='Forecast', linestyle='--')
    plt.title(f'ARMA({order[0]},{order[1]}) Forecast for {name} (10-Minute Ahead)')
    plt.xlabel('Time')
    plt.ylabel('Close Price')
    plt.legend()
    plt.grid(True)
    plt.show()

    return model

# Fit ARMA models
robinhood_arma = fit_arma_model(robinhood_diff, 'Robinhood')
gm_arma = fit_arma_model(gm_diff, 'General Motors')

# ARIMA Model (assuming ARIMA(2,1,2) if non-stationary, else ARIMA(2,0,2))
def fit_arima_model(series, name, order=(2,1,2)):
    model = ARIMA(series, order=order).fit()
    print(f'ARIMA({order[0]},{order[1]},{order[2]}) Model for {name}:')
    print(model.summary())

    # Forecast
    forecast = model.forecast(steps=2)  # 10 minutes = 2 steps at 5-min frequency

    # Plot
    plt.figure(figsize=(12, 6))
    plt.plot(series[-50:], label='Actual')
    forecast_index = pd.date_range(start=series.index[-1] + timedelta(minutes=5), periods=2, freq='5T')
    plt.plot(forecast_index, forecast, label='Forecast', linestyle='--')
    plt.title(f'ARIMA({order[0]},{order[1]},{order[2]}) Forecast for {name} (10-Minute Ahead)')
    plt.xlabel('Time')
    plt.ylabel('Close Price')
    plt.legend()
    plt.grid(True)
    plt.show()

    return model

# Fit ARIMA models (use differenced data if non-stationary)
robinhood_arima = fit_arima_model(robinhood_df['Close'], 'Robinhood', order=(2,1,2) if not robinhood_stationary else (2,0,2))
gm_arima = fit_arima_model(gm_df['Close'], 'General Motors', order=(2,1,2) if not gm_stationary else (2,0,2))

# Summary of Findings
print("\nSummary:")
print("1. Stationarity: Robinhood and General Motors prices are likely non-stationary (based on ADF test). Differencing was applied where necessary.")
print("2. Cointegration: The stocks may or may not be cointegrated (based on p-value).")
print("3. Models: AR, ARMA, and ARIMA models were fitted. Forecasts for the next 10 minutes were generated.")
print("4. Visualizations: Plots show the original series, differenced series (if applicable), and forecasts for each model.")